package net.seanv.stonegameserver.dto.validation;

import jakarta.validation.Constraint;
import jakarta.validation.Payload;
import java.lang.annotation.*;

@Constraint(validatedBy = FieldsNotEqualValidator.class)
@Target(ElementType.TYPE)
@Retention(RetentionPolicy.RUNTIME)
@Repeatable(FieldsNotEqual.List.class)
public @interface FieldsNotEqual {

    String message() default ""; // optional, autogenerated if empty
    Class<?>[] groups() default {};
    Class<? extends Payload>[] payload() default {};

    String field1();
    String field2();

    @Target({ ElementType.TYPE })
    @Retention(RetentionPolicy.RUNTIME)
    @interface List {
        FieldsNotEqual[] value();
    }
}
