version: '3.8'

services:
  app:
    build: .
    container_name: server
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/game
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=dbpass
    depends_on:
      - db

  site:
    build: ../leaderboard/.
    container_name: website
    ports:
      - "8081:8081"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/game
      - SPRING_DATASOURCE_USERNAME=user
      - SPRING_DATASOURCE_PASSWORD=dbpass
    depends_on:
      - db

  db:
    image: postgres
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: game
      POSTGRES_USER: user
      POSTGRES_PASSWORD: dbpass
    volumes:
      - postgres-data:/var/lib/postgresql/data
#      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  postgres-data: